import turtle

screen = turtle.Screen()
screen.bgcolor('lightpink')

t=turtle.Turtle()

t.penup()
t.goto(0,200)
t.pendown()
t.write("All About Me", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(0,-50)
t.pendown()
t.write("Ella Richards", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(0,-300)
t.pendown()
t.pensize(5)
t.pencolor('pale turquoise')
t.fillcolor('pale turquoise')
t.begin_fill()
t.circle(87)
t.end_fill()
t2=turtle.Turtle()
t2.penup()
turtle.addshape("blue1.gif")
t2.shape("blue1.gif")
t2.goto(100,-150)
a=t2.stamp()

t2.penup()
turtle.addshape("blue2.gif")
t2.shape("blue2.gif")
t2.goto(150,-500)
a=t2.stamp()
enter = input("Press Enter to Start")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('medium aquamarine')
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Favorite Foods", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(-160,40)
t.write("Pasta", font=("Arial", 20, "bold"), align="center")
t.penup()
t.goto(0,40)
t.write("tacos", font=("Arial", 20, "bold"), align="center")
t.penup()
t.goto(140,40)
t.write("Canes", font=("Arial", 20, "bold"), align="center")
t.penup()
t.goto(-75, 105)
t.fillcolor('purple')
t.pendown()
t.begin_fill()
t.forward(150)
t.left(90)
t.forward(100)
t.left(90)
t.forward(150)
t.left(90)
t.forward(100)
t.end_fill()

t2.penup()
turtle.addshape("canes.gif")
t2.shape("canes.gif")
t2.goto(100,-100)
a=t2.stamp()

t2.penup()
t2.goto(-100,-100)
turtle.addshape("pasta.gif")
t2.shape("pasta.gif")
t2.goto(-100,-100)
a=t2.stamp()


t2.penup()
turtle.addshape("tacos.gif")
t2.shape("tacos.gif")
t2.goto(100,-100)
a=t2.stamp()





enter = input("Press Enter to go to next slide")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('powder blue')
t.pencolor('black')
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Hobbies", font=("Arial", 35, "bold"), align="center")
t.penup()
t.penup()
t.goto(-250,40)
t.write("Tennis", font=("Arial", 15, "bold"), align="center")
t.penup()
t.goto(-150,40)
t.write("Video Games", font=("Arial", 15, "bold"), align="center")
t.penup()
t.goto(-40,40)
t.write("Shopping", font=("Arial", 15, "bold"), align="center")
t.penup()
t.goto(140,40)
t.write("Listening to Music", font=("Arial", 15, "bold"), align="center")
t.penup()
t.pencolor('black')

t.penup()
t.goto(60,10)
t.fillcolor('mint cream')
t.pendown()
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()

turtle.addshape("tennis.gif")
t2.shape("tennis.gif")
t2.goto(100,-200)
a=t2.stamp()





t2.penup()
turtle.addshape("game.gif")
t2.shape("game.gif")
t2.goto(-200,-200)
a=t2.stamp()
t2.goto(-100,-200)


turtle.addshape("shop.gif")
t2.shape("shop.gif")
t2.goto(200,-300)
a=t2.stamp()


turtle.addshape("music.gif")
t2.shape("music.gif")
t2.goto(300,-250)
a=t2.stamp()

enter=input("Press Enter to go to next slide")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('medium slate blue')
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Favorite Movie", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(-10,100)
t.pencolor('navy')
t.fillcolor('navy')
t.penup()
t.goto(-10,100)
t.pencolor('old lace')
t.fillcolor('powder blue')
t.pendown()
t.begin_fill()
t.circle(30,180)
t.end_fill()
t.penup()
t.goto(0,-50)
t.pendown()
t.pencolor("black")
t.write("Coraline", font=("Arial", 35, "bold"), align="")
t.penup()
t.goto(140,40)
t.write("Red Notice", font=("Arial", 15, "bold"), align="center")


t2.penup()
turtle.addshape("coraline.gif")
t2.shape("coraline.gif")
t2.goto(100,-200)
a=t2.stamp()

t2.penup()
turtle.addshape("rednotice.gif")
t2.shape("rednotice.gif")
t2.goto(100,-100)
a=t2.stamp()





t2.penup()
turtle.addshape("movie.gif")
t2.shape("movie.gif")
t2.goto(-100,-200)
a=t2.stamp()
t2.goto(-100,-200)
enter=input("Press Enter to go to next slide")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('pale green')
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Favorite Sport", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(0,-50)
t.pendown()
t.write("Tennis", font=("Arial", 35, "bold"), align="center")
t.fillcolor('pink')
t.begin_fill()
t.goto(-50,-10)
t.pendown()
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.end_fill()
t2.penup()

t2.penup()
turtle.addshape("stennis.gif")
t2.shape("stennis.gif")
t2.goto(100,-200)
a=t2.stamp()


t2.penup()
turtle.addshape("figureskate.gif")
t2.shape("figureskate.gif")
t2.goto(-100,-200)
a=t2.stamp()
t2.goto(-100,-200)

enter=input("Press Enter to go to next slide")
t.clear()
t2.clearstamps()
